<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>libpjsua2.maui</RootNamespace>
        <AssemblyName>pjsua2maui.win</AssemblyName>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
	    <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
    </ItemGroup>
    <PropertyGroup>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <PropertyGroup Condition="'$(IsOfficialBuild)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>
 
    <PropertyGroup>
        <PackageId>libpjsua2maui.win</PackageId>
        <Version>2.17.0.2</Version>
        <AssemblyVersion>2.17.0.2</AssemblyVersion>
        <FileVersion>2.17.0.2</FileVersion>
        <Title>PJSIP bindings for .NET MAUI</Title>
        <Authors>Weslley Murdock</Authors>
        <Company>Remote Code Hub</Company>
        <Copyright>Copyright ©2026 Remote Code Hub</Copyright>
        <PackageTags>sip;voip;pjsip;pjlib;pjsua;pjsua2;libpjsua2;pjproject;pjsua2maui;maui;net</PackageTags>
        <Description>##PJSIP pjsua2 bindings for pjsua2
Provides .NET bindings of library libpjsua2 by pjsip for Windows.
Pjsip version used is 2.17, using thirdy party libs such as openh264, openssl, opus and bcg729
#NOTES
Min Win version : 10.0.17763.0
Target Win version : 11.0

This library enables working with the pjsip SIP stack implementation for make voip
calls.
For this release see notes -
https://github.com/remotecodehub/libpjsua2maui/blob/main/README.md and
https://github.com/remotecodehub/libpjsua2maui/blob/main/CHANGELOG.md
        </Description>
        <PackageProjectUrl>https://github.com/remotecodehub/libpjsua2maui</PackageProjectUrl>
        <RepositoryUrl>https://github.com/remotecodehub/libpjsua2maui.git</RepositoryUrl>
    </PropertyGroup>
    
	<ItemGroup>
        <None Update="..\LICENSE">
            <PackagePath>\</PackagePath>
            <Pack>True</Pack>
        </None>
        <None Update="..\README.md">
            <PackagePath>\</PackagePath>
            <Pack>True</Pack>
        </None>
        <None Update="..\..\docs\README.md">
            <PackagePath>\docs</PackagePath>
            <Pack>True</Pack>
        </None>
	</ItemGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>portable</DebugType>
	</PropertyGroup>
</Project>