<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-android</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>libpjsua2.maui</RootNamespace>
		<AssemblyName>pjsua2maui.android</AssemblyName> 
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">23.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion>23</TargetPlatformMinVersion>
		<UseMaui>true</UseMaui>
		<IsOfficialBuild>false</IsOfficialBuild>
	</PropertyGroup>
 
    <PropertyGroup>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <PropertyGroup Condition="'$(IsOfficialBuild)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>
 
	<PropertyGroup>
		<PackageId>libpjsua2maui.android</PackageId>
	    <Version>2.17.0.1</Version>
		<AssemblyVersion>2.17.0.1</AssemblyVersion>
		<FileVersion>2.17.0.1</FileVersion>
		<Title>PJSIP bindings for .NET MAUI</Title>
	    <Authors>Weslley Murdock</Authors>
	    <Company>Remote Code Hub</Company>
		<Copyright>Copyright ©2026 Remote Code Hub</Copyright>
		<PackageTags>sip;voip;pjsip;pjlib;pjsua;pjsua2;libpjsua2;pjproject;pjsua2maui;maui;net</PackageTags>
		<Description>##PJSIP libpjsua2 bindings for .NET MAUI
Provides .NET bindings of library libpjsua2 by pjsip for Android.
Pjsip version used is 2.17, using thirdy party libs such as openh264, openssl, opus and bcg729
#NOTES
Min Android version : 9.0 (API 28)
Target Android version : 16.0 (API 36)

This library enables working with the pjsip SIP stack implementation for make voip
calls.
For this release see notes -
https://github.com/remotecodehub/libpjsua2maui/blob/main/README.md and
https://github.com/remotecodehub/libpjsua2maui/blob/main/CHANGELOG.md
		</Description>
		<PackageProjectUrl>https://github.com/remotecodehub/libpjsua2maui</PackageProjectUrl>
		<RepositoryUrl>https://github.com/remotecodehub/libpjsua2maui.git</RepositoryUrl>
	</PropertyGroup>
		
	<ItemGroup>
        <None Update="..\LICENSE">
            <PackagePath>\</PackagePath>
            <Pack>True</Pack>
        </None>
        <None Update="..\README.md">
            <PackagePath>\</PackagePath>
            <Pack>True</Pack>
        </None>
        <None Update="..\..\docs\README.md">
            <PackagePath>\docs</PackagePath>
            <Pack>True</Pack>
        </None>
	</ItemGroup>
	
</Project>