//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace libpjsua2.maui {

public enum pj_file_access {
  PJ_O_RDONLY = 4353,
  PJ_O_WRONLY = 4354,
  PJ_O_RDWR = 4355,
  PJ_O_APPEND = 4360,
  PJ_O_CLOEXEC = 4356,
  PJ_O_ASYNC = 512,
  PJ_O_SEQUENTIAL = 1024,
  PJ_O_RANDOM = 2048
}

}
