//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace libpjsua2.maui {

public enum pj_ssl_cert_direct_type {
  PJ_SSL_CERT_DIRECT_NONE = 0,
  PJ_SSL_CERT_DIRECT_OPENSSL_EVP_PKEY = 1,
  PJ_SSL_CERT_DIRECT_OPENSSL_X509_CERT = 2
}

}
