//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace libpjsua2.maui {

public enum pjmedia_conf_op_type {
  PJMEDIA_CONF_OP_UNKNOWN,
  PJMEDIA_CONF_OP_ADD_PORT,
  PJMEDIA_CONF_OP_REMOVE_PORT,
  PJMEDIA_CONF_OP_CONNECT_PORTS,
  PJMEDIA_CONF_OP_DISCONNECT_PORTS,
  PJMEDIA_CONF_OP_ADJUST_CONN_LEVEL
}

}
