//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace libpjsua2.maui {

public enum pjmedia_ai_event_type {
  PJMEDIA_AI_EVENT_CONNECTED,
  PJMEDIA_AI_EVENT_DISCONNECTED,
  PJMEDIA_AI_EVENT_TRANSCRIPT,
  PJMEDIA_AI_EVENT_RESPONSE_START,
  PJMEDIA_AI_EVENT_RESPONSE_DONE,
  PJMEDIA_AI_EVENT_SPEECH_STARTED,
  PJMEDIA_AI_EVENT_SPEECH_STOPPED
}

}
