//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace libpjsua2.maui {

public class VideoRecorder : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VideoRecorder(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VideoRecorder obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VideoRecorder obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VideoRecorder() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pjsua2PINVOKE.delete_VideoRecorder(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VideoRecorder() : this(pjsua2PINVOKE.new_VideoRecorder(), true) {
    SwigDirectorConnect();
  }

  public void createVideoRecorder(string file_name, int max_size, MediaFormatVideo vid_fmt, MediaFormatAudio aud_fmt, uint options) {
    pjsua2PINVOKE.VideoRecorder_createVideoRecorder__SWIG_0(swigCPtr, file_name, max_size, MediaFormatVideo.getCPtr(vid_fmt), MediaFormatAudio.getCPtr(aud_fmt), options);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

  public void createVideoRecorder(string file_name, int max_size, MediaFormatVideo vid_fmt, MediaFormatAudio aud_fmt) {
    pjsua2PINVOKE.VideoRecorder_createVideoRecorder__SWIG_1(swigCPtr, file_name, max_size, MediaFormatVideo.getCPtr(vid_fmt), MediaFormatAudio.getCPtr(aud_fmt));
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

  public void createVideoRecorder(string file_name, int max_size, MediaFormatVideo vid_fmt) {
    pjsua2PINVOKE.VideoRecorder_createVideoRecorder__SWIG_2(swigCPtr, file_name, max_size, MediaFormatVideo.getCPtr(vid_fmt));
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

  public void createVideoRecorder(string file_name, int max_size) {
    pjsua2PINVOKE.VideoRecorder_createVideoRecorder__SWIG_3(swigCPtr, file_name, max_size);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

  public void createVideoRecorder(string file_name) {
    pjsua2PINVOKE.VideoRecorder_createVideoRecorder__SWIG_4(swigCPtr, file_name);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
  }

  public VideoMedia getVideoMedia() {
    VideoMedia ret = new VideoMedia(pjsua2PINVOKE.VideoRecorder_getVideoMedia(swigCPtr), true);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public AudioMedia getAudioMedia() {
    AudioMedia ret = new AudioMedia(pjsua2PINVOKE.VideoRecorder_getAudioMedia(swigCPtr), true);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void onMaxSize() {
    if (SwigDerivedClassHasMethod("onMaxSize", swigMethodTypes0)) pjsua2PINVOKE.VideoRecorder_onMaxSizeSwigExplicitVideoRecorder(swigCPtr); else pjsua2PINVOKE.VideoRecorder_onMaxSize(swigCPtr);
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("onMaxSize", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateVideoRecorder_0(SwigDirectorMethodonMaxSize);
    pjsua2PINVOKE.VideoRecorder_director_connect(swigCPtr, swigDelegate0);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo[] methodInfos = this.GetType().GetMethods(
        global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance);
    foreach (global::System.Reflection.MethodInfo methodInfo in methodInfos) {
      if (methodInfo.DeclaringType == null)
        continue;

      if (methodInfo.Name != methodName)
        continue;

      var parameters = methodInfo.GetParameters();
      if (parameters.Length != methodTypes.Length)
        continue;

      bool parametersMatch = true;
      for (var i = 0; i < parameters.Length; i++) {
        if (parameters[i].ParameterType != methodTypes[i]) {
          parametersMatch = false;
          break;
        }
      }

      if (!parametersMatch)
        continue;

      if (methodInfo.IsVirtual && (methodInfo.DeclaringType.IsSubclassOf(typeof(VideoRecorder))) &&
        methodInfo.DeclaringType != methodInfo.GetBaseDefinition().DeclaringType) {
        return true;
      }
    }

    return false;
  }

  private void SwigDirectorMethodonMaxSize() {
    onMaxSize();
  }

  public delegate void SwigDelegateVideoRecorder_0();

  private SwigDelegateVideoRecorder_0 swigDelegate0;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] {  };
}

}
