//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace libpjsua2.maui {

public enum pjmedia_vid_stream_rc_method {
  PJMEDIA_VID_STREAM_RC_NONE = 0,
  PJMEDIA_VID_STREAM_RC_SIMPLE_BLOCKING = 1,
  PJMEDIA_VID_STREAM_RC_SEND_THREAD = 2
}

}
