//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace libpjsua2.maui {

public enum pjsua_snd_dev_mode {
  PJSUA_SND_DEV_SPEAKER_ONLY = 1,
  PJSUA_SND_DEV_NO_IMMEDIATE_OPEN = 2
}

}
