//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace libpjsua2.maui {

public class AuthChallenge : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AuthChallenge(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AuthChallenge obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(AuthChallenge obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~AuthChallenge() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pjsua2PINVOKE.delete_AuthChallenge(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public AuthChallenge() : this(pjsua2PINVOKE.new_AuthChallenge(), true) {
  }

  public AuthChallenge defer() {
    global::System.IntPtr cPtr = pjsua2PINVOKE.AuthChallenge_defer(swigCPtr);
    AuthChallenge ret = (cPtr == global::System.IntPtr.Zero) ? null : new AuthChallenge(cPtr, true);
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int respond() {
    int ret = pjsua2PINVOKE.AuthChallenge_respond__SWIG_0(swigCPtr);
    return ret;
  }

  public int respond(AuthCredInfoVector creds) {
    int ret = pjsua2PINVOKE.AuthChallenge_respond__SWIG_1(swigCPtr, AuthCredInfoVector.getCPtr(creds));
    if (pjsua2PINVOKE.SWIGPendingException.Pending) throw pjsua2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int abandon() {
    int ret = pjsua2PINVOKE.AuthChallenge_abandon(swigCPtr);
    return ret;
  }

  public bool isValid() {
    bool ret = pjsua2PINVOKE.AuthChallenge_isValid(swigCPtr);
    return ret;
  }

}

}
