//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace libpjsua2.maui {

public enum pj_file_access {
  PJ_O_RDONLY = 0x1101,
  PJ_O_WRONLY = 0x1102,
  PJ_O_RDWR = 0x1103,
  PJ_O_APPEND = 0x1108,
  PJ_O_CLOEXEC = 0x1104,
  PJ_O_ASYNC = 0x200,
  PJ_O_SEQUENTIAL = 0x400,
  PJ_O_RANDOM = 0x800
}

}
