//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace libpjsua2.maui {

public enum pj_qos_wmm_prio {
  PJ_QOS_WMM_PRIO_BULK_EFFORT,
  PJ_QOS_WMM_PRIO_BULK,
  PJ_QOS_WMM_PRIO_VIDEO,
  PJ_QOS_WMM_PRIO_VOICE
}

}
