//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace libpjsua2.maui {

public enum pj_ssl_cert_lookup_type {
  PJ_SSL_CERT_LOOKUP_NONE,
  PJ_SSL_CERT_LOOKUP_SUBJECT,
  PJ_SSL_CERT_LOOKUP_FINGERPRINT,
  PJ_SSL_CERT_LOOKUP_FRIENDLY_NAME
}

}
