//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace libpjsua2.maui {

public enum pjmedia_vid_conf_op_type {
  PJMEDIA_VID_CONF_OP_UNKNOWN,
  PJMEDIA_VID_CONF_OP_ADD_PORT,
  PJMEDIA_VID_CONF_OP_REMOVE_PORT,
  PJMEDIA_VID_CONF_OP_CONNECT_PORTS,
  PJMEDIA_VID_CONF_OP_DISCONNECT_PORTS,
  PJMEDIA_VID_CONF_OP_UPDATE_PORT
}

}
