//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace libpjsua2.maui {

public enum pjsua_invalid_id_const_ {
  PJSUA_INVALID_ID = -1
}

}
