//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace libpjsua2.maui {

public class VideoMediaOpParam : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VideoMediaOpParam(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VideoMediaOpParam obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(VideoMediaOpParam obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~VideoMediaOpParam() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pjsua2PINVOKE.delete_VideoMediaOpParam(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public VideoMediaAddInfo addInfo {
    set {
      pjsua2PINVOKE.VideoMediaOpParam_addInfo_set(swigCPtr, VideoMediaAddInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = pjsua2PINVOKE.VideoMediaOpParam_addInfo_get(swigCPtr);
      VideoMediaAddInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new VideoMediaAddInfo(cPtr, false);
      return ret;
    } 
  }

  public VideoMediaRemoveInfo removeInfo {
    set {
      pjsua2PINVOKE.VideoMediaOpParam_removeInfo_set(swigCPtr, VideoMediaRemoveInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = pjsua2PINVOKE.VideoMediaOpParam_removeInfo_get(swigCPtr);
      VideoMediaRemoveInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new VideoMediaRemoveInfo(cPtr, false);
      return ret;
    } 
  }

  public VideoMediaConnectInfo connectInfo {
    set {
      pjsua2PINVOKE.VideoMediaOpParam_connectInfo_set(swigCPtr, VideoMediaConnectInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = pjsua2PINVOKE.VideoMediaOpParam_connectInfo_get(swigCPtr);
      VideoMediaConnectInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new VideoMediaConnectInfo(cPtr, false);
      return ret;
    } 
  }

  public VideoMediaDisconnectInfo disconnectInfo {
    set {
      pjsua2PINVOKE.VideoMediaOpParam_disconnectInfo_set(swigCPtr, VideoMediaDisconnectInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = pjsua2PINVOKE.VideoMediaOpParam_disconnectInfo_get(swigCPtr);
      VideoMediaDisconnectInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new VideoMediaDisconnectInfo(cPtr, false);
      return ret;
    } 
  }

  public VideoMediaUpdateInfo updateInfo {
    set {
      pjsua2PINVOKE.VideoMediaOpParam_updateInfo_set(swigCPtr, VideoMediaUpdateInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = pjsua2PINVOKE.VideoMediaOpParam_updateInfo_get(swigCPtr);
      VideoMediaUpdateInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new VideoMediaUpdateInfo(cPtr, false);
      return ret;
    } 
  }

  public VideoMediaOpParam() : this(pjsua2PINVOKE.new_VideoMediaOpParam(), true) {
  }

}

}
