//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace libpjsua2.maui {

public class AudioMediaOpParam : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AudioMediaOpParam(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(AudioMediaOpParam obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(AudioMediaOpParam obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~AudioMediaOpParam() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pjsua2PINVOKE.delete_AudioMediaOpParam(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public AudioMediaAddInfo addInfo {
    set {
      pjsua2PINVOKE.AudioMediaOpParam_addInfo_set(swigCPtr, AudioMediaAddInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = pjsua2PINVOKE.AudioMediaOpParam_addInfo_get(swigCPtr);
      AudioMediaAddInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new AudioMediaAddInfo(cPtr, false);
      return ret;
    } 
  }

  public AudioMediaRemoveInfo removeInfo {
    set {
      pjsua2PINVOKE.AudioMediaOpParam_removeInfo_set(swigCPtr, AudioMediaRemoveInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = pjsua2PINVOKE.AudioMediaOpParam_removeInfo_get(swigCPtr);
      AudioMediaRemoveInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new AudioMediaRemoveInfo(cPtr, false);
      return ret;
    } 
  }

  public AudioMediaConnectInfo connectInfo {
    set {
      pjsua2PINVOKE.AudioMediaOpParam_connectInfo_set(swigCPtr, AudioMediaConnectInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = pjsua2PINVOKE.AudioMediaOpParam_connectInfo_get(swigCPtr);
      AudioMediaConnectInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new AudioMediaConnectInfo(cPtr, false);
      return ret;
    } 
  }

  public AudioMediaDisconnectInfo disconnectInfo {
    set {
      pjsua2PINVOKE.AudioMediaOpParam_disconnectInfo_set(swigCPtr, AudioMediaDisconnectInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = pjsua2PINVOKE.AudioMediaOpParam_disconnectInfo_get(swigCPtr);
      AudioMediaDisconnectInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new AudioMediaDisconnectInfo(cPtr, false);
      return ret;
    } 
  }

  public AudioMediaOpParam() : this(pjsua2PINVOKE.new_AudioMediaOpParam(), true) {
  }

}

}
