//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace libpjsua2.maui {

public class OnAudioMediaOpCompletedParam : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OnAudioMediaOpCompletedParam(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OnAudioMediaOpCompletedParam obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(OnAudioMediaOpCompletedParam obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~OnAudioMediaOpCompletedParam() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pjsua2PINVOKE.delete_OnAudioMediaOpCompletedParam(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public pjmedia_conf_op_type opType {
    set {
      pjsua2PINVOKE.OnAudioMediaOpCompletedParam_opType_set(swigCPtr, (int)value);
    } 
    get {
      pjmedia_conf_op_type ret = (pjmedia_conf_op_type)pjsua2PINVOKE.OnAudioMediaOpCompletedParam_opType_get(swigCPtr);
      return ret;
    } 
  }

  public int status {
    set {
      pjsua2PINVOKE.OnAudioMediaOpCompletedParam_status_set(swigCPtr, value);
    } 
    get {
      int ret = pjsua2PINVOKE.OnAudioMediaOpCompletedParam_status_get(swigCPtr);
      return ret;
    } 
  }

  public AudioMediaOpParam opParam {
    set {
      pjsua2PINVOKE.OnAudioMediaOpCompletedParam_opParam_set(swigCPtr, AudioMediaOpParam.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = pjsua2PINVOKE.OnAudioMediaOpCompletedParam_opParam_get(swigCPtr);
      AudioMediaOpParam ret = (cPtr == global::System.IntPtr.Zero) ? null : new AudioMediaOpParam(cPtr, false);
      return ret;
    } 
  }

  public OnAudioMediaOpCompletedParam() : this(pjsua2PINVOKE.new_OnAudioMediaOpCompletedParam(), true) {
  }

}

}
