//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace libpjsua2.maui {

public class OnAuthChallengeParam : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal OnAuthChallengeParam(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(OnAuthChallengeParam obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(OnAuthChallengeParam obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~OnAuthChallengeParam() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pjsua2PINVOKE.delete_OnAuthChallengeParam(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int accId {
    set {
      pjsua2PINVOKE.OnAuthChallengeParam_accId_set(swigCPtr, value);
    } 
    get {
      int ret = pjsua2PINVOKE.OnAuthChallengeParam_accId_get(swigCPtr);
      return ret;
    } 
  }

  public int callId {
    set {
      pjsua2PINVOKE.OnAuthChallengeParam_callId_set(swigCPtr, value);
    } 
    get {
      int ret = pjsua2PINVOKE.OnAuthChallengeParam_callId_get(swigCPtr);
      return ret;
    } 
  }

  public SipRxData rdata {
    set {
      pjsua2PINVOKE.OnAuthChallengeParam_rdata_set(swigCPtr, SipRxData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = pjsua2PINVOKE.OnAuthChallengeParam_rdata_get(swigCPtr);
      SipRxData ret = (cPtr == global::System.IntPtr.Zero) ? null : new SipRxData(cPtr, false);
      return ret;
    } 
  }

  public AuthChallenge challenge {
    get {
      global::System.IntPtr cPtr = pjsua2PINVOKE.OnAuthChallengeParam_challenge_get(swigCPtr);
      AuthChallenge ret = (cPtr == global::System.IntPtr.Zero) ? null : new AuthChallenge(cPtr, false);
      return ret;
    } 
  }

  public OnAuthChallengeParam() : this(pjsua2PINVOKE.new_OnAuthChallengeParam(), true) {
  }

}

}
