//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace libpjsua2.maui {

public enum pjsip_auth_algorithm_type {
  PJSIP_AUTH_ALGORITHM_NOT_SET = 0,
  PJSIP_AUTH_ALGORITHM_MD5,
  PJSIP_AUTH_ALGORITHM_SHA256,
  PJSIP_AUTH_ALGORITHM_SHA512_256,
  PJSIP_AUTH_ALGORITHM_AKAV1_MD5,
  PJSIP_AUTH_ALGORITHM_AKAV2_MD5,
  PJSIP_AUTH_ALGORITHM_COUNT
}

}
