//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace libpjsua2.maui {

public class SockOpt : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SockOpt(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SockOpt obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(SockOpt obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~SockOpt() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pjsua2PINVOKE.delete_SockOpt(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int level {
    set {
      pjsua2PINVOKE.SockOpt_level_set(swigCPtr, value);
    } 
    get {
      int ret = pjsua2PINVOKE.SockOpt_level_get(swigCPtr);
      return ret;
    } 
  }

  public int optName {
    set {
      pjsua2PINVOKE.SockOpt_optName_set(swigCPtr, value);
    } 
    get {
      int ret = pjsua2PINVOKE.SockOpt_optName_get(swigCPtr);
      return ret;
    } 
  }

  public SockOpt() : this(pjsua2PINVOKE.new_SockOpt__SWIG_0(), true) {
  }

  public SockOpt(int level, int optName, int optVal) : this(pjsua2PINVOKE.new_SockOpt__SWIG_1(level, optName, optVal), true) {
  }

  public void setOptValInt(int opt_val) {
    pjsua2PINVOKE.SockOpt_setOptValInt(swigCPtr, opt_val);
  }

}

}
