name: build

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
    
  pull_request:
    types: [opened, synchronize, reopened]  
  
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
  build:
    runs-on: macos-latest
    name: build
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
 
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources
        
      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '17'
         
      - name: Download Android & iOS Artifacts
        run: |
          echo "Android ..."
          curl -L -o ./libpjsua2.maui.so.tar.gz https://github.com/weslleymurdock/libpjsua2-android/releases/download/v2.14.1.1/libpjsua2.tar.gz
          tar -xzvf libpjsua2.maui.so.tar.gz 
          mkdir -p ./libpjsua2.maui.android/org/pjsip
          mkdir -p ./libpjsua2.maui.android/pjsua2maui
          mkdir -p ./libpjsua2.runtime.android/lib/
          mv -v ./home/runner/libpjsua2/lib/libpjsua2.maui.android/*.cs ./libpjsua2.maui.android/pjsua2maui
          rm -rf ./home/runner/libpjsua2/lib/java/org/pjsip/pjsua2
          mv -v ./home/runner/libpjsua2/lib/java/org/pjsip/* ./libpjsua2.maui.android/org/pjsip/
          mv -v ./home/runner/libpjsua2/lib/* ./libpjsua2.runtime.android/lib/
          echo "iOS ..."
          curl -L -o ./libpjsua2.maui.a.tar.gz https://github.com/weslleymurdock/libpjsua2-ios/releases/download/v2.14.1.1/libpjsua2.tar.gz
          tar -xzvf libpjsua2.maui.a.tar.gz
          mkdir -p ./libpjsua2.maui.ios/pjsua2maui
          mkdir -p ./libpjsua2.runtime.ios/lib/fat 
          mv -v ./libpjsua2/lib/pjsua2maui/pjsua2/* ./libpjsua2.maui.ios/pjsua2maui
          lipo -create -output ./libpjsua2.runtime.ios/lib/fat/libpjsua2.a ./libpjsua2/lib/**/*.a 
          rm -rf ./libpjsua2 libpjsua2.maui.a.tar.gz

      - name: Restore Dependencies
        run: | 
          dotnet restore src/libpjsua2.maui.android/libpjsua2.maui.android.csproj
          dotnet restore src/libpjsua2.maui.ios/libpjsua2.maui.ios.csproj

      - name: Build MAUI Android
        run: dotnet publish src/libpjsua2.maui.android/libpjsua2.maui.android.csproj -c Release -f net9.0-android --no-restore
       
      - name: Build MAUI iOS
        run: dotnet publish src/libpjsua2.maui.ios/libpjsua2.maui.ios.csproj -c Release -f net9.0-ios --no-restore
